on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  set-asana-task-status:
    runs-on: ubuntu-latest
    name: Set Asana task status
    steps:
      - name: Set Asana task status
        uses: OneSignal/GitHubAsanaStatusAction@main
        with:
          asana-api-token: ${{ secrets.ASANA_API_TOKEN }}
